export const taskConstants = {
  ADD_TASK: 'NEW_TASK',
  ADD_TASK_FAIL: 'ADD_TASK_FAIL',
  READ_TASKS: 'READ_TASKS',
  READ_TASKS_FAIL: 'READ_TASKS_FAIL',
  UPDATE_TASKS: 'UPDATE_TASKS',
  UPDATE_TASKS_FAIL: 'UPDATE_TASKS_FAIL',
  DELETE_TASKS: 'DELETE_TASKS',
  DELETE_TASKS_FAIL: 'DELETE_TASKS_FAIL',
};
